import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { AnimatePresence, motion } from 'framer-motion'
import { Heart, Search, ShoppingBag, X, Minus, Plus } from 'lucide-react'

const whatsapp='https://wa.me/971551495060'
const W='https://woodmart.xtemos.com/perfumes/wp-content/uploads/sites/32'
const img={
  logoWhite:`${W}/2025/11/prf-logotype-white.svg`, logoBlack:`${W}/2025/11/prf-logotype-black.svg`,
  heroBg:`${W}/2025/12/prf-slide-1-bg-ov.jpg.webp`, heroBottle:`${W}/2025/11/prf-slide-1-bottle-1-opt.png.webp`,
  etheria:`${W}/2025/11/prf-collection-etheria.jpg.webp`, opus:`${W}/2025/11/prf-collection-opus-essence.jpg`,
  banner2:`${W}/2025/11/prf-slide-banner-bg-2.jpg.webp`, banner3:`${W}/2025/11/prf-slide-banner-bg-3.jpg.webp`,
  abyss:`${W}/2025/11/abyss-bleu.jpeg.webp`, abyss1:`${W}/2025/11/abyss-bleu-1.jpeg.webp`, abyss2:`${W}/2025/11/abyss-bleu-2.jpeg.webp`, abyss3:`${W}/2025/11/abyss-bleu-3.jpeg.webp`,
  amber:`${W}/2025/11/amber-bloom.jpeg.webp`, amber2:`${W}/2025/11/amber-bloom-2.jpeg.webp`, ember:`${W}/2025/11/ember-glow.jpeg.webp`, amethyst:`${W}/2025/11/amethyst-haze.jpeg.webp`,
  arctic:`${W}/2025/11/arctic-dusk.jpeg`, celestial:`${W}/2025/11/celestial-frost.jpeg.webp`, surge:`${W}/2025/11/celestial-surge-3.jpeg.webp`, glacier:`${W}/2025/11/glacier-bloom-2.jpeg.webp`,
}

const sizes=[{l:'100ml',m:1},{l:'50ml',m:.5},{l:'2ml Sample',m:.08}]
const products=[
  {id:'abyss-bleu',name:'Abyss Bleu',full:'Abyss Bleu 100ml',family:['Aldehyde','Fresh'],collection:'Nocturne Essence',desc:'A dark, mysterious scent evoking the ocean’s deepest depths.',price:250,img:img.abyss,gallery:[img.abyss,img.abyss1,img.abyss2,img.abyss3]},
  {id:'abyss-bleu-sample',name:'Abyss Bleu',full:'Abyss Bleu 2ml Sample',family:['Aldehyde','Fresh'],collection:'Nocturne Essence',desc:'A dark, mysterious scent evoking the ocean’s deepest depths.',price:20,img:img.abyss3,gallery:[img.abyss3,img.abyss,img.abyss1]},
  {id:'abyss-bleu-50ml',name:'Abyss Bleu',full:'Abyss Bleu 50ml',family:['Aldehyde','Fresh'],collection:'Nocturne Essence',desc:'A dark, mysterious scent evoking the ocean’s deepest depths.',price:125,img:img.abyss2,gallery:[img.abyss2,img.abyss1,img.abyss]},
  {id:'amber-bloom',name:'Amber Bloom',full:'Amber Bloom 100ml',family:['Amber','Floral'],collection:'Étheria',desc:'Soft amber, blooming jasmine and clean musks with a radiant warm trail.',price:250,img:img.amber,gallery:[img.amber,img.amber2]},
  {id:'amber-bloom-sample',name:'Amber Bloom',full:'Amber Bloom 2ml Sample',family:['Amber','Floral'],collection:'Étheria',desc:'Soft amber, blooming jasmine and clean musks with a radiant warm trail.',price:20,img:img.amber2,gallery:[img.amber2,img.amber]},
  {id:'ember-glow',name:'Ember Glow',full:'Ember Glow 100ml',family:['Spicy','Amber'],collection:'Opus Essence',desc:'Radiant blend of citrus, florals, and warm musks, evoking a starlit night.',price:250,img:img.ember,gallery:[img.ember,img.amethyst]},
  {id:'amethyst-haze',name:'Amethyst Haze',full:'Amethyst Haze 100ml',family:['Floral','Fresh'],collection:'Étheria',desc:'A luminous, ethereal fragrance that captures the serene beauty of dawn.',price:250,img:img.amethyst,gallery:[img.amethyst,img.amber]},
]
const fromCollection=[
  {id:'arctic-dusk',full:'Arctic Dusk 50ml',price:125,img:img.arctic},
  {id:'celestial-frost',full:'Celestial Frost 100ml',price:250,img:img.celestial},
  {id:'celestial-surge',full:'Celestial Surge 2ml Sample',price:20,img:img.surge},
  {id:'glacier-bloom',full:'Glacier Bloom 2ml Sample',price:20,img:img.glacier},
]
const familyTiles=['Floral','Woody','Amber','Chypre','Leather','Aldehyde','Spicy','Fougere']
const money=n=>`$${Number(n).toFixed(2)}`
const getP=id=>products.find(p=>p.id===id)||products[0]

const LangContext=createContext(null)
const useLang=()=>useContext(LangContext)
function LangProvider({children}){const [l,setL]=useState(()=>localStorage.getItem('nc-l')||'en');useEffect(()=>{localStorage.setItem('nc-l',l);document.documentElement.lang=l;document.documentElement.dir=l==='ar'?'rtl':'ltr'},[l]);return <LangContext.Provider value={{l,toggle:()=>setL(x=>x==='ar'?'en':'ar')}}>{children}</LangContext.Provider>}

const CartContext=createContext(null)
const useCart=()=>useContext(CartContext)
function CartProvider({children}){
  const [items,setItems]=useState(()=>{try{return JSON.parse(localStorage.getItem('nc-c')||'[]')}catch{return[]}})
  const [open,setOpen]=useState(false)
  useEffect(()=>localStorage.setItem('nc-c',JSON.stringify(items)),[items])
  const add=(p,sl='100ml',q=1)=>{const s=sizes.find(x=>x.l===sl)||sizes[0];setItems(v=>{const hit=v.find(x=>x.id===p.id&&x.sl===sl);if(hit)return v.map(x=>x.id===p.id&&x.sl===sl?{...x,q:x.q+q}:x);return[...v,{id:p.id,na:p.full||p.name,img:p.img,sl,pr:Math.round((p.price||250)*s.m),q}]});setOpen(true)}
  const up=(id,sl,q)=>setItems(v=>v.map(x=>x.id===id&&x.sl===sl?{...x,q:Math.max(1,q)}:x))
  const rm=(id,sl)=>setItems(v=>v.filter(x=>!(x.id===id&&x.sl===sl)))
  const sub=items.reduce((s,x)=>s+x.pr*x.q,0),cnt=items.reduce((s,x)=>s+x.q,0)
  const v=useMemo(()=>({items,open,setOpen,add,up,rm,sub,cnt}),[items,open,sub,cnt])
  return <CartContext.Provider value={v}>{children}</CartContext.Provider>
}

function WA(){return <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347M12.05 21.785a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884"/></svg>}

function Header(){const {cnt,setOpen}=useCart();const {l,toggle}=useLang();const home=useLocation().pathname==='/'
  return <header className={`site-header ${home?'over-hero':''}`}><div className="site-bar"><Link to="/" className="brand-logo"><span>NICHE CENTER.</span></Link><nav><a href="#new">New</a><a href="#family">Fragrances</a><a href="#journal">Journal</a><a href="#about">About Us</a></nav><div className="head-actions"><button><Search size={20}/>Search</button><button onClick={toggle}>{l==='ar'?'EN':'AR'}</button><a href={whatsapp} target="_blank" rel="noreferrer"><WA/></a><button onClick={()=>setOpen(true)}>Cart {cnt}</button></div></div></header>}

function Hero(){return <section className="wm-hero"><img className="hero-bg" src={img.heroBg} alt=""/><button className="hero-arrow left">‹</button><button className="hero-arrow right">›</button><div className="hero-content"><img className="hero-bottle" src={img.heroBottle} alt="Aurora Flame"/><h1>New Fragrance in the<br/>Opus Essence</h1><Link className="black-btn" to="/product/abyss-bleu">Buy Now</Link></div><div className="hero-pages"><b>01</b><span>02</span><span>03</span></div></section>}

function ProductCard({p,i}){const {add}=useCart();return <motion.article className="wm-card" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.025,duration:.22}}><Link to={`/product/${p.id}`}><h3>{p.full}</h3><img src={p.img} alt={p.full}/><p>{money(p.price)}</p></Link><div className="card-actions"><button onClick={()=>add(p)}>＋</button><button><Heart size={17}/></button></div></motion.article>}
function ProductGrid({title='New In',items=products.slice(0,6),filters=false}){return <section className="wm-section" id={title==='New In'?'new':undefined}><div className="section-title"><h2>{title}</h2>{filters&&<div className="tabs"><button>All</button><button>For Her</button><button>For Him</button></div>}</div><div className="wm-grid">{items.map((p,i)=><ProductCard key={p.id} p={p} i={i}/>)}</div></section>}

function Family(){return <section className="wm-section family" id="family"><h2>Shop by Olfactory Family</h2><div className="family-buttons">{familyTiles.map(f=><a key={f} href="#new">{f}</a>)}</div><div className="marquee"><span>Ethereal</span><i>✦</i><span>Sensory</span><i>✦</i><span>Signature</span><i>✦</i><span>Ethereal</span></div><div className="featured-fragrance"><div><h2>Ember Glow</h2><p>Radiant blend of citrus, florals, and warm musks, evoking the magic of a starlit night in Los Angeles. Luminous, sensual, and endlessly captivating.</p></div><ProductCard p={products[5]} i={0}/></div></section>}

function Home(){return <main><Hero/><ProductGrid title="New In"/><Family/><ProductGrid title="Promotional Offers" items={products.slice(0,4)} filters/><section className="collections"><article style={{backgroundImage:`url(${img.banner2})`}}><h2>Nocturne Essence</h2><p>A collection of fresh, luminous scents inspired by mystery of nightfall.</p><a>View Collection</a></article><article style={{backgroundImage:`url(${img.banner3})`}}><h2>Étheria</h2><p>Delicate, weightless fragrances that capture the essence of air and light.</p><a>View Collection</a></article></section><Journal/></main>}
function Journal(){return <section className="wm-section journal" id="journal"><h2>Journal Articles</h2><div className="journal-row"><article><span>28 Oct 2025</span><h3>Scent & Sensibility</h3></article><article><span>12 Oct 2025</span><h3>Notes of Elegance</h3></article><article><span>08 Oct 2025</span><h3>The Perfume Journal</h3></article></div><div className="insta"><h2>Connect to our<br/>Instagram</h2><a href="https://www.instagram.com/niche_center/">@niche_center</a></div></section>}

function ProductPage(){const {id}=useParams();const p=getP(id);const {add}=useCart();const [sel,setSel]=useState(0);const [qty,setQty]=useState(1);useEffect(()=>{document.title=`${p.full} - Niche Center`},[p]);const gallery=p.gallery||[p.img]
  return <main className="product-page"><section className="single-product"><div className="gallery-masonry"><img className="main-product-img" src={gallery[0]} alt={p.full}/><div className="sub-gallery"><img src={gallery[1]||gallery[0]} alt=""/><img src={gallery[2]||gallery[0]} alt=""/></div><div className="video-tile"></div></div><aside className="product-summary"><h1>{p.full}</h1><p className="short-desc">{p.desc}</p><div className="size-row"><b>Size :</b>{sizes.map((s,i)=><button key={s.l} className={sel===i?'active':''} onClick={()=>setSel(i)}>{s.l}</button>)}</div><p className="single-price">{money(Math.round(p.price*sizes[sel].m))}</p><div className="purchase-row"><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={13}/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus size={13}/></button></div><button className="black-wide" onClick={()=>add(p,sizes[sel].l,qty)}>Add To Cart</button><button className="outline-wide" onClick={()=>add(p,sizes[sel].l,qty)}>Buy Now</button><button className="heart-only"><Heart size={21}/></button></div><div className="details-table"><p><b>Collection</b><span>{p.collection}</span></p><p><b>Olfactive Family</b><span>{p.family.join(', ')}</span></p><p><b>Perfume</b><span>For Him</span></p></div></aside></section><section className="collection-story"><h2>Étheria Collection</h2><div className="video-hero" style={{backgroundImage:`url(${img.etheria})`}}><span>▷</span></div><p>Aurora Haze is a luminous, ethereal fragrance that captures the serene beauty of dawn. Opening with delicate citrus and dewy florals, it unfolds into a heart of soft amber and blooming jasmine, evoking the first golden rays of sunlight. A warm base of creamy sandalwood and subtle musk lingers on the skin, wrapping you in a gentle, radiant embrace.</p><div className="notes"><div><h3>Top Notes:</h3><p>Bergamot, Pimento Berry, Oregano</p></div><div><h3>Heart Notes:</h3><p>Amber, Citrus, Frankincense, Vanilla</p></div><div><h3>Base Notes:</h3><p>Oud, Leather, Patchouli, Sandalwood</p></div></div></section><section className="wm-section from"><h2>From Collection</h2><div className="wm-grid four">{fromCollection.map((x,i)=><ProductCard key={x.id} p={x} i={i}/>)}</div></section></main>}

function CartDrawer(){const {open,setOpen,items,up,rm,sub}=useCart();const nav=useNavigate();return <AnimatePresence>{open&&<><motion.div className="drawer-bg" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)}/><motion.aside className="cart-drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}}><div className="drawer-head"><h3>Shopping cart</h3><button onClick={()=>setOpen(false)}><X size={18}/></button></div>{items.length===0?<div className="empty-cart"><ShoppingBag/><h4>No products in the cart.</h4><Link to="/" onClick={()=>setOpen(false)} className="black-wide">Return To Shop</Link></div>:<><div className="drawer-items">{items.map(x=><div className="drawer-item" key={x.id+x.sl}><img src={x.img} alt=""/><div><b>{x.na}</b><small>{x.sl}</small><button onClick={()=>rm(x.id,x.sl)}>Remove</button></div><div><strong>{money(x.pr*x.q)}</strong><span><button onClick={()=>up(x.id,x.sl,x.q-1)}>-</button>{x.q}<button onClick={()=>up(x.id,x.sl,x.q+1)}>+</button></span></div></div>)}</div><div className="drawer-foot"><p><span>Subtotal</span><b>{money(sub)}</b></p><button className="black-wide" onClick={()=>{setOpen(false);nav('/checkout')}}>Checkout</button></div></>}</motion.aside></>}</AnimatePresence>}
function Checkout(){const {items,sub}=useCart();return <main className="checkout-page"><div className="steps"><span>Shopping cart</span><b>Checkout</b><span>Order complete</span></div><h1>Checkout</h1>{items.length===0?<div className="empty-check"><h2>Your cart is currently empty.</h2><p>Before proceed to checkout you must add some products to your shopping cart.</p><Link className="black-btn" to="/">Return to shop</Link></div>:<div className="checkout-layout"><form><h2>Billing details</h2><label>First name<input required/></label><label>Last name<input required/></label><label>Country / Region<input defaultValue="United Arab Emirates"/></label><label>Phone<input required/></label><label>Email address<input type="email"/></label><button className="black-wide">Place order</button></form><aside><h2>Your order</h2>{items.map(x=><p key={x.id+x.sl}><span>{x.na} × {x.q}</span><b>{money(x.pr*x.q)}</b></p>)}<strong><span>Total</span><span>{money(sub)}</span></strong></aside></div>}</main>}
function Footer(){return <footer className="wm-footer" id="about"><div><h2>NICHE CENTER.</h2><div><h3>At Niche Center Perfumery, we see perfume as more than just a scent — it is identity, memory and emotion captured in a bottle.</h3></div></div><div className="footer-links"><section><h3>Insider Access</h3><p>Receive exclusive content and be the first to know about product launches and special announcements.</p><div><input placeholder="Your email address"/><button>Sign Up</button></div></section><section><a>About Us</a><a>Contact Us</a><a>F.A.Q.</a><a>Blog</a></section><section><a>Refund</a><a>Cookies</a><a>Terms of use</a><a>Privacy</a></section></div><p className="copy">Niche Center © 2026 created for UAE.</p></footer>}
function Shell(){const loc=useLocation();useEffect(()=>scrollTo(0,0),[loc.pathname]);return <><Header/><CartDrawer/><AnimatePresence mode="wait"><motion.div key={loc.pathname} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.18}}><Routes location={loc}><Route path="/" element={<Home/>}/><Route path="/product/:id" element={<ProductPage/>}/><Route path="/checkout" element={<Checkout/>}/></Routes></motion.div></AnimatePresence><Footer/><a className="float-wa" href={whatsapp} target="_blank" aria-label="WhatsApp"><WA/></a></>}
export default function App(){return <LangProvider><CartProvider><Shell/></CartProvider></LangProvider>}
